### ISSUE TITLE
0.0.7 doesn't work in Foundry 10 anymore

### ISSUE THREAD

**Issue by GambetTV** [Sk1mble/zsync#2]
Not sure if it's supposed to, but it auto-updates so that suggests it's supposed to be compatible with v10. In any event, in v10 when I click on a token that overlaps with another token, it pops to the top on my screen, but it doesn't sync up with my players' screens, and from there perspective nothing pops up.

**Comment by Sk1mble** [comment]
This is odd, while I had to completely change the behaviour in v11 it's gated behind an or statement that uses the same code as before if the version of Foundry is older than 11.293. I don't have a v10 installation at the moment so this will be hard for me to test, could you possibly insert this in line 51 of zsync.js and let me know if a popup occurs on the player's machine when you click on a token in v10:

ui.notifications.info(data.scene_id)

You could also manually revert to the version here: https://raw.githubusercontent.com/Sk1mble/zsync/v0.0.6/module.json

**Comment by Sk1mble** [comment]
Hi, please try v0.0.8. I

**Comment by GambetTV** [comment]
That fixed it!
